### ISSUE TITLE
This plugin not needed anymore, Neovim 0.5 has fixed block paste.

### ISSUE THREAD

**Issue by bluz71** [lambdalisue/pastefix.vim#2]
[Neovim PR14848](https://github.com/neovim/neovim/pull/14848) was merged prior to Neovim 0.5 (a couple days ago).

It fixes block paste. You may want to retire this plugin, e.g. keep it active for Neovim 0.4.4 and earlier but update the README that for Neovim 0.5 and later this plugin is not required.

Cheers.

**Comment by bluz71** [comment]
Closing, since my issue is not ongoing, just a notification.

**Comment by lambdalisue** [comment]
Thanks. PR is welcome 👍
